export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_ORDER_PRODUCT = 'DELETE_ORDER_PRODUCT';
export const ADD_ORDER_PRODUCT = 'ADD_ORDER_PRODUCT';
export const SUBTRACT_ORDER_PRODUCT = 'SUBTRACT_ORDER_PRODUCT';
